import "res/fonts/IBMPlexSans-Regular.ttf";
import "res/fonts/IBMPlexSans-Bold.ttf";

export global Palette {
    out property <color> success: #4effa6;
    out property <color> danger: #f96161;
    out property <color> background: #28282f;
    out property <color> tile: #3d3d4c;
    out property <color> text: #6a6a78;
    out property <color> text_on_tile: #a7a6ad;
    out property <color> text_on_tile2: #e5d6d6;
}

export global Typo {
    out property <length> label_size: 18px;
}

export component Tile inherits Rectangle {
    background: Palette.tile;
    border-radius: 20px;
}

export component Tick inherits Text {
    font-size: 18px;
    color: Palette.text_on_tile;
    font-weight: 700;
    horizontal-alignment: right;
}

export component MainWindow inherits Window {
    width: 480px;
    height: 320px;
    title: "Open Vaporphase";
    default-font-family: "IBM Plex Sans";

    in property <bool> is_running: true;
    in property <string> temperature: "0.0";
    in property <string> time_remaining: "13:12";
    in property <[float]> past_temperatures: [];
    in property <int> n_past_temperatures: 20;
    Rectangle {
        width: parent.width;
        height: parent.height;
        background: Palette.background;

        VerticalLayout {
            padding: 16px;
            spacing: 6px;
            HorizontalLayout {
                alignment: space-between;
                Text {
                    text: is_running ? "RUNNING" : "IDLE";
                    font-size: Typo.label_size;
                    color: is_running ? Palette.success : Palette.text;
                    font-weight: 700;
                }

                Text {
                    text: "Open Vaporphase α0.1";
                    font-size: Typo.label_size;
                    color: Palette.text;
                }
            }

            GridLayout {
                spacing: 12px;
                height: 260px;

                Tile {
                    width: 60%;
                    row: 0;
                    col: 0;
                    rowspan: 2;
                    colspan: 2;

                    HorizontalLayout {
                        padding: 20px;
                        VerticalLayout {
                            Tick {
                                text: "0";
                            }

                            Tick {
                                text: "75";
                            }

                            Tick {
                                text: "150";
                            }

                            Tick {
                                text: "225";
                            }

                            Tick {
                                text: "300";
                            }
                        }

                        Path {
                            width: 80%;
                            height: 100%;
                            stroke-width: 2px;

                            MoveTo {
                                x: 0%;
                                y: 100%;
                            }

                            for temp[i] in past_temperatures: id := LineTo {
                                x: (i / (past_temperatures.length - 1)) * 100%;
                                y: 100% - (temp / 300.0) * 100%;
                            }
                        }
                    }
                }

                Tile {
                    row: 0;
                    col: 2;

                    VerticalLayout {
                        height: 100%;
                        padding: 20px;
                        spacing: -20px;

                        Text {
                            text: temperature + "°C";
                            color: Palette.success;
                            font-size: 28px;
                            font-weight: 700;
                        }

                        Text {
                            text: time_remaining;
                            color: Palette.text_on_tile;
                            font-size: 28px;
                        }
                    }
                }

                Tile {
                    row: 1;
                    col: 2;
                    background: Palette.danger;
                    height: 50%;
                    TouchArea {
                        Text {
                            text: "STOP";
                            font-size: 28px;
                            font-weight: 700;
                            color: Palette.text_on_tile2;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }
            }
        }
    }
}
